echo VAI CRIAR INDICES: %DATE% %TIME%
mongo CriaIndices.js
echo TERMINOU CRIAÇÃO DE INDICES: %DATE% %TIME%

echo VAI INICIAR TESTES CONSULTAS (COM INDEX): %DATE% %TIME%
mongo Consultas.js
echo TERMINOU TESTES CONSULTAS (COM INDEX): %DATE% %TIME%
